### PR TITLE
Doc updates

### LINKED ISSUE #35: Document --bundle-add and --bundle-remove
Please provide examples for these cmdline options.

### PR DESCRIPTION
**Pull request by battlemidget**
Added spellbooks for core spells, cleaned up troubleshooting, cleaned up usage

Fixes #35
Fixes https://github.com/conjure-up/conjure-up/issues/1430

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

### CODE REVIEW

**Comment by battlemidget** [comment]
@evilnick Ideally, I'd like to have this point to devel and also to a "stable" branch and have the redirects point to /en/stable for the latest stable docs. Then going forward I can just work from the master/devel branch and cherry pick into the stable branch.

**Comment by evilnick** [comment]
I was thinking along similar lines for the organisation of branches. I can sort out some redirects. It *may* be useful to simply rename the master branch as 'devel' to avoid having to change the tooling and/or backporting from master to a different devel branch.

**Comment by battlemidget** [comment]
@evilnick totally open to having just a devel and a stable branch and just work between those 2 when updates need to be made.

**Comment by battlemidget** [comment]
Hey @evilnick not sure if youre sprinting this week but let me know if you need anything from me. Ive got some other documentation I want to cleanup and add and wanted to keep the commits/PRs small.

Thanks!

**Pull request merged**
