### PR TITLE
Test new documentation_builder template on conjure-up docs

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
# Don't merge

Testing how the proposed new documentation_builder template looks on the conjure-up docs. https://github.com/canonical-webteam/documentation-builder/pull/110

## QA

- Pull code
- `./run`
- Select `update-template` from the version dropdown
- Check the following things:
  - [ ] Overall design looks good (@kwm14)
  - [ ] Header navigation: Search works as before, title shows and is formatted correctly
  - [ ] Sidebar navigation: 3 levels deep items looks good, selected state shows, sticks to top of viewport
  - [ ] Table of contents: Works properly (as before), sticks to top of viewport
  - [ ] Versions: Selecting different versions works, disabled pages work (i.e. versions that don't contain the current page are greyed out)
  - [ ] Media (images) loads in properly

### Before

docs conjure-up io_2 4 0_en_ 1

### After

0 0 0 0_8204_update-template_en_

### CODE REVIEW

**Comment by battlemidget** [comment]
Question, will this address the menu for sub headers being out of alignment?

image

**Comment by evilnick** [comment]
@battlemidget It *should* do, along with some other stuff

**Comment by Caleb-Ellis** [comment]
@battlemidget It does! The idea now is to have everything expanded from the start, like in https://docs.vanillaframework.io/en/

screenshot_2

Still have some issues to iron out so it works across all the different Ubuntu docs but hopefully I can release v1.6 of documentation_builder (with this new template) soon

**Comment by battlemidget** [comment]
Hi, any eta when we can get this pushed live? I need to update the code in conjure-up to point to the new documentation links.

Thanks!

**Comment by Caleb-Ellis** [comment]
Hi @battlemidget! Please don't let this PR get in the way of any docs updates - I've only been using it for testing purposes. documentation-builder v1.6.0 is getting released later today, at which point the docs pages can be updated with new styling whenever is convenient for you

**Comment by Caleb-Ellis** [comment]
Closing as documentation-builder 1.6.0 is now out

**Comment by tvansteenburgh** [comment]
@evilnick @Caleb-Ellis It looks like these updates still aren't published on the live site - can you guys make that happen please?

**Comment by evilnick** [comment]
@tvansteenburgh the docs were last built 3rd July, so I guess the documentation-builder update took a bit longer to push. I have rebuilt them now though, let me know if there is anything that doesn't look right

**Pull request closed without merging**
