### PR TITLE
LXD doc updates

### PR DESCRIPTION
**Pull request by battlemidget**
Needs signoff from Charm Engineering in addition to Doc team.

This updates the documentation around LXD setup to be more descriptive in configuring LXD prior to running conjure-up.

### CODE REVIEW

**Comment by battlemidget** [comment]
@johnsca @kwmonroe

**Comment by evilnick** [comment]
I'm going to fix a few things up in the branch before merging this - thanks for all the feedback

**Comment by battlemidget** [comment]
Hey @evilnick any word on this PR?

**Comment by evilnick** [comment]
Hi, sorry about the delay. I'll land this then do any fixups

**Pull request merged**
